---
- name: Install Packages for AD auth
  ansible.builtin.yum:
    name:
      - krb5-workstation
      - sssd-krb5
    state: present

- name: Copy Kerberos Config to /etc/krb5.conf
  ansible.builtin.copy:
    src: files/krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
    setype: krb5_conf_t

- name: Copy sssd Config to /etc/sssd/
  ansible.builtin.copy:
    src: files/sssd.conf
    dest: /etc/sssd/
    owner: root
    group: root
    mode: '0600'
    setype: sssd_conf_t
  notify: Restart sssd

- name: Ensure sssd is Selected by authselect
  ansible.builtin.command:
    cmd: authselect current -r
  register: authselect_current
  changed_when: false
  failed_when: false

- name: Configure authselect for sssd
  ansible.builtin.command:
    cmd: /usr/bin/authselect select sssd --force
  changed_when: true
  notify: Restart sssd
  when: "'sssd' not in authselect_current.stdout"
