---
cockpit_packages:
  - cockpit
  - cockpit-bridge
  - cockpit-networkmanager
  - cockpit-packagekit
  - cockpit-selinux
  - cockpit-storaged
  - cockpit-system
  - cockpit-ws
  - cockpit-sosreport
  - cockpit-kdump
cockpit_enabled: true
cockpit_started: true
cockpit_port: 9090
cockpit_manage_firewall: false
